FROM node:20-alpine AS dependencies
WORKDIR /my-project
COPY package.json  ./

RUN npm install
#--frozen-lockfile

FROM node:20-alpine AS builder
WORKDIR /my-project
ENV NODE_ENV=production
COPY . .
COPY --from=dependencies /my-project/node_modules ./node_modules
COPY ./.env.local ./.env.local
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /my-project
#ENV NODE_ENV production

# If you are using a custom next.config.js file, uncomment this line.
# COPY --from=builder /my-project/next.config.js ./
COPY --from=builder /my-project/public ./public
COPY --from=builder /my-project/.next ./.next
COPY --from=builder /my-project/node_modules ./node_modules
COPY --from=builder /my-project/package.json ./package.json
COPY --from=builder /my-project/.env.local ./

EXPOSE 3000

ENV PORT=3000

ENV HOSTNAME=0.0.0.0

CMD ["npm","run","start"]
