import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import ClientProviders from "@/components/client-providers";
import { cookies } from "next/headers";
import data from "@/lib/data";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setting = data.setting
  const countryCodeCookie = (await cookies()).get('user-country-code')
  const contryCode = countryCodeCookie ? countryCodeCookie.value : '752'
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased remove-scrollbar",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <ClientProviders setting={{ ...setting, countryCode: Number(contryCode) }}>
          {children}
        </ClientProviders>
        {/* <SessionProvider >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </ThemeProvider>
        </SessionProvider> */}
      </body>
    </html>
  );
}
